services:
  ssh_honeypot:
    build: ./ssh-server
    container_name: ssh_honeypot
    restart: unless-stopped
    ports:
      - "2223:2223"
    env_file:
      - .env
    volumes:
      - ssh_cache:/app/cache

  http_honeypot:
    build: ./http
    container_name: http_honeypot
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
    env_file:
      - .env
    volumes:
      - http_cache:/app/cache

  db_honeypot:
    build: ./database
    container_name: db_honeypot
    restart: unless-stopped
    ports:
      - "2224:2224"
    env_file:
      - .env
    volumes:
      - db_cache:/app/cache

  # kafka:
  #   image: confluentinc/cp-kafka:7.8.3
  #   container_name: kafka
  #   restart: unless-stopped
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_KRAFT_MODE: "true"
  #     CLUSTER_ID: "qwerty12345"

volumes:
  ssh_cache:
  http_cache:
  db_cache:
